version: '3.3'

services:
  node:
    build: .
    expose:
      - "3000"
    depends_on:
      - ocpu
    networks:
      - my-network

  ocpu:
    image: frafortu/ocpu:v1.0.0
    expose:
      - "8004"  
    networks:
      - my-network
    command: /bin/sh -c "service cron start && /usr/lib/rstudio-server/bin/rserver && apachectl -DFOREGROUND & Rscript /home/opencpu/GEVIS/gevis-cache.R"

  nginx:
    image: nginx:latest
    ports:
      - "11765:11765"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html   
    depends_on:
      - node
      - ocpu
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
